/**
 * Foundry Platform SDK Integration
 *
 * Uses @osdk/client + @osdk/foundry for real Foundry stack integration.
 * Falls back to standalone mode when env vars are not configured.
 *
 * Required env vars for Foundry mode:
 *   FOUNDRY_STACK       e.g. https://your-stack.palantirfoundry.com
 *   FOUNDRY_CLIENT_ID   OAuth2 client ID from Developer Console
 *   FOUNDRY_CLIENT_SECRET
 *   FOUNDRY_ONTOLOGY_RID  ri.ontology.main.ontology.xxxxx
 *   FOUNDRY_AIP_AGENT_RID ri.aip-agents.main.agent.xxxxx (optional)
 */

export interface FoundryConfig {
  stack: string;
  clientId: string;
  clientSecret: string;
  ontologyRid: string;
  aipAgentRid?: string;
}

export function getFoundryConfig(): FoundryConfig | null {
  const stack    = process.env.FOUNDRY_STACK;
  const clientId = process.env.FOUNDRY_CLIENT_ID;
  const secret   = process.env.FOUNDRY_CLIENT_SECRET;
  const ontRid   = process.env.FOUNDRY_ONTOLOGY_RID;
  if (!stack || !clientId || !secret || !ontRid) return null;
  return {
    stack, clientId, clientSecret: secret, ontologyRid: ontRid,
    aipAgentRid: process.env.FOUNDRY_AIP_AGENT_RID,
  };
}

export function isFoundryConfigured(): boolean {
  return getFoundryConfig() !== null;
}

/**
 * Create a server-side Foundry Platform SDK client.
 * Uses confidential OAuth (client credentials) — safe for API routes.
 */
export async function createFoundryClient() {
  const config = getFoundryConfig();
  if (!config) throw new Error("Foundry not configured");

  // Dynamic import because these are ESM-only packages
  const [{ createPlatformClient }, { createConfidentialOauthClient }] = await Promise.all([
    import("@osdk/client"),
    import("@osdk/oauth"),
  ]);

  const auth = createConfidentialOauthClient(
    config.clientId,
    config.clientSecret,
    config.stack,
    undefined, // scopes — undefined = use defaults
  );

  return { client: createPlatformClient(config.stack, auth), config };
}

// ── Ontology Object Types (mirrors what generated OSDK would produce) ─────────
// These match the Foundry Ontology object type API names.
// On a real stack, these would be auto-generated by `npx osdk generate`.

export const OBJECT_TYPES = {
  COUNTY_REGION:    "county-region",
  HAZARD_EVENT:     "hazard-event",
  RESPONSE_TASK:    "response-task",
  RESPONSE_RESOURCE:"response-resource",
  CRITICAL_FACILITY:"critical-facility",
} as const;

export const ACTION_TYPES = {
  CREATE_TASK:        "create-response-task",
  ASSIGN_RESOURCE:    "assign-resource-to-task",
  UPDATE_TASK_STATUS: "update-task-status",
  APPROVE_TASK:       "approve-response-task",
  CANCEL_TASK:        "cancel-response-task",
  APPLY_WEIGHTS:      "apply-scoring-weights",
} as const;

// ── Foundry Ontology object shapes ───────────────────────────────────────────
// These are what OntologyObjectsV2.list() returns for each object type.

export interface FoundryCountyRegion {
  __rid: string;
  countyFips: string;
  name: string;
  state: string;
  population: number;
  vulnerabilityScore: number;
  riskScore: number;
  alertLevel: string;
  declarationStatus: string;
  impactedPopulationEstimate: number;
}

export interface FoundryHazardEvent {
  __rid: string;
  eventId: string;
  eventType: string;
  severity: string;
  issuedAt: string;
  expiresAt: string;
  affectedCountyFips: string; // comma-separated
}

export interface FoundryResponseTask {
  __rid: string;
  taskId: string;
  taskType: string;
  title: string;
  targetCountyFips: string;
  priorityScore: number;
  status: string;
  assignedResourceId: string | null;
  triggerReason: string;
  deadlineHours: number;
  createdAt: string;
}

export interface FoundryResponseResource {
  __rid: string;
  resourceId: string;
  resourceType: string;
  label: string;
  baseFips: string;
  baseName: string;
  status: string;
  assignedTaskId: string | null;
  assignedFips: string | null;
  latitude: number;
  longitude: number;
}
